### ISSUE TITLE
 Could not load './lib/GetAddress'

### ISSUE THREAD

**Issue by Gudis24** [getAddress/autocomplete#3]
https://github.com/getAddress/autocomplete/blob/868e0f6771f57cb4eb0c03f28150937363e5a4c2/package.json#L5C1-L5C30

It seems, that you removed GetAddress, in effect there is an error while building the project.
`@parcel/resolver-default: Could not load './lib/GetAddress' from module 'getaddress-autocomplete' found in package.json#main`

**Comment by LeePaulSmith** [comment]
Thanks for letting us know.  Getaddress.js was replaced with Index.js this has now been corrected.
